name: Probe

on:
  push:
    branches: [fix/cd-transform-outputs]
    paths:
      - ".github/workflows/probe.yml"
      - ".github/workflows/_probe-mid.yml"
      - ".github/workflows/_probe-inner.yml"

jobs:
  mid:
    uses: ./.github/workflows/_probe-mid.yml
